# Generated by Django 3.2.3 on 2021-07-13 07:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('date', models.DateField(verbose_name='День рождения')),
                ('num_tel', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'ordering': ['username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
