# Generated by Django 3.2.3 on 2021-07-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210713_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='date',
            new_name='date123',
        ),
    ]
