# Generated by Django 3.2.3 on 2021-07-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_users_date123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date123',
        ),
    ]
