# Generated by Django 3.2.3 on 2021-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_date123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото'),
        ),
    ]
