# Generated by Django 3.2.3 on 2021-07-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='num_tel',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
