# Generated by Django 3.2.3 on 2021-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_num_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(related_name='_users_users_friends_+', to='users.Users', verbose_name='Друзья'),
        ),
    ]
