# Generated by Django 3.2.3 on 2021-08-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_users_friends_+', to='users.Users', verbose_name='Друзья'),
        ),
    ]
