# Generated by Django 3.2.3 on 2021-08-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
