# Generated by Django 3.2.3 on 2021-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_users_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_users_users_subscribers_+', to='users.Users', verbose_name='Подписчики'),
        ),
    ]
