# Generated by Django 3.2.3 on 2021-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_users_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, verbose_name='Я')),
                ('user', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время заявки')),
            ],
            options={
                'verbose_name': 'Подтверждение',
                'verbose_name_plural': 'Подтверждения',
                'ordering': ['owner'],
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='subscribers',
        ),
    ]
