# Generated by Django 3.2.3 on 2021-08-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210831_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubscribers',
            name='user',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь'),
        ),
    ]
