# Generated by Django 3.2.3 on 2021-09-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210906_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_user',
            field=models.CharField(max_length=50, verbose_name='qweqe'),
        ),
    ]
