# Generated by Django 3.2.3 on 2021-09-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_messages_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.users', verbose_name='Отправитель'),
        ),
    ]
