# Generated by Django 3.2.3 on 2021-09-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
