# Generated by Django 3.2.3 on 2021-09-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
