# Generated by Django 3.2.3 on 2021-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubscribers',
            name='escape',
            field=models.BooleanField(default=False, verbose_name='Просмотрел(-а)'),
        ),
    ]
