version: "3.9"

services:
  postgres_db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: database
    networks:
      - socialNetwork

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - os_data:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_db
      - redis
    container_name: main
    networks:
      - socialNetwork

  redis:
    image: redis:latest
    command: "redis-server"
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - socialNetwork

  celery:
    build: .
    command: "celery -A config worker -l INFO"
    volumes:
      - celery_data:/home/user
    depends_on:
      - web
      - redis
    container_name: celery
    networks:
      - socialNetwork
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
  os_data:
  celery_data:

networks:
  socialNetwork:
