# Generated by Django 3.2.3 on 2021-07-09 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('slug', models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=150, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dislike', models.IntegerField(default=0, verbose_name='Дизлайки')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'db_table': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=150, unique=True, verbose_name='URL')),
                ('num_pub', models.IntegerField(default=0, verbose_name='Количество записей')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Аватарка')),
                ('published', models.ManyToManyField(blank=True, to='main.Published', verbose_name='публикации')),
                ('users', models.ManyToManyField(blank=True, related_name='_main_groups_users_+', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.published', verbose_name='Публикация')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'Комментарии',
            },
        ),
    ]
