# Generated by Django 3.2.3 on 2021-08-04 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_alter_users_num_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=150, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='groups/', verbose_name='Аватарка')),
                ('users', models.ManyToManyField(blank=True, related_name='groups_users', to='users.Users', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=150, unique=True, verbose_name='URL')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='published/', verbose_name='Фото')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('readers', models.CharField(max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_published', to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'db_table': 'Публикации',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Звезда Рейтинг',
                'verbose_name_plural': 'Звезда Рейтинги',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.published', verbose_name='Публикация')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratingstar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.published', verbose_name='Публикация')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
    ]
