# Generated by Django 3.2.3 on 2021-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='published',
            field=models.ManyToManyField(to='main.Published', verbose_name='Группа'),
        ),
    ]
