# Generated by Django 3.2.3 on 2021-07-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_groups_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='published',
        ),
        migrations.AddField(
            model_name='published',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа'),
        ),
    ]
