# Generated by Django 3.2.3 on 2021-07-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210715_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', verbose_name='Группа'),
        ),
    ]
