# Generated by Django 3.2.3 on 2021-08-11 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210804_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=150, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='LikeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comments', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-date'],
            },
        ),
    ]
