# Generated by Django 3.2.3 on 2021-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_published_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='photo',
            field=models.ImageField(upload_to='groups/', verbose_name='Аватарка'),
        ),
    ]
