# Generated by Django 3.2.3 on 2021-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_num_tel'),
        ('main', '0006_alter_comments_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='like',
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(related_name='like', to='users.Users', verbose_name='Лайки'),
        ),
    ]
