# Generated by Django 3.2.3 on 2021-08-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_num_tel'),
        ('main', '0007_auto_20210811_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='users.Users', verbose_name='Лайки'),
        ),
    ]
