# Generated by Django 3.2.3 on 2021-08-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comments_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='users',
            new_name='users1',
        ),
        migrations.DeleteModel(
            name='LikeComments',
        ),
    ]
