# Generated by Django 3.2.3 on 2021-07-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_options'),
        ('main', '0008_auto_20210717_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.published', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь'),
        ),
    ]
