# Generated by Django 3.2.3 on 2021-08-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210811_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='users1',
            new_name='users',
        ),
    ]
