# Generated by Django 3.2.3 on 2021-07-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_options'),
        ('main', '0009_auto_20210719_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='published',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.published', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_main_groups_users_+', to='users.Users', verbose_name='Пользователи'),
        ),
    ]
