# Generated by Django 3.2.3 on 2021-08-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_users1_comments_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
