# Generated by Django 3.2.3 on 2021-07-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210721_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments', verbose_name='Ответы'),
        ),
    ]
