# Generated by Django 3.2.3 on 2021-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comments_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='answers',
        ),
    ]
