# Generated by Django 3.2.3 on 2021-08-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_options'),
        ('main', '0012_rating_ratingstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_group', to='users.users', verbose_name='Создатель группы'),
        ),
    ]
