# Generated by Django 3.2.3 on 2021-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_groups_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=40, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='published',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='published',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Такой URL уже существует!!!'}, help_text='<i>Заполняется автоматически!</i>', max_length=40, unique=True, verbose_name='URL'),
        ),
    ]
