# Generated by Django 3.2.3 on 2021-07-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_groups_num_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
