# Generated by Django 3.2.3 on 2021-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_num_tel'),
        ('main', '0014_auto_20210727_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='published',
            options={'ordering': ['-date'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='published',
            name='dislike',
        ),
        migrations.AddField(
            model_name='published',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to='users.Users', verbose_name='Дизлайки'),
        ),
        migrations.RemoveField(
            model_name='published',
            name='like',
        ),
        migrations.AddField(
            model_name='published',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='users.Users', verbose_name='Лайки'),
        ),
    ]
