# Generated by Django 3.2.3 on 2021-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210831_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='biography',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='published',
            name='biography',
            field=models.TextField(verbose_name='Биография'),
        ),
    ]
