# Generated by Django 3.2.3 on 2021-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210802_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='published',
            name='dislike',
        ),
        migrations.AddField(
            model_name='published',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.RemoveField(
            model_name='published',
            name='like',
        ),
        migrations.AddField(
            model_name='published',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
